stages:
    - docker-build

build mobalpa-blog:
    stage: docker-build
    script:
      - export IMAGE_TAG="$CI_JOB_NAME"
      - export IMAGE_TAG_V="$CI_COMMIT_REF_NAME"
      - echo $IMAGE_TAG
      - echo $IMAGE_TAG_V
      #- docker build -t $IMAGE_TAG -t $IMAGE_TAG_V .






        


      

