stages:
    - docker-build
    - test
    - analyze
    - deploy

build mobalpa-blog:
    stage: docker-build
    before_script:
      - apk update
      - apk add --no-cache bash
    script:
      #- echo $CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA
      - docker build -t $CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA .
      - chmod +x cleanup-container.sh
      - bash cleanup-container.sh
      - docker run -d --name web -p 8080:80 --link dbm:mysql $CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA

build mobalpa-test:
    stage: test
    allow_failure: true
    script:
      - docker exec web bash /usr/local/apache2/htdocs/analyze.sh


build mobalpa-analyze:
    stage: analyze
    script:
      - docker cp web:/tmp/analyze.log .
      - echo "ERROR=$(grep 'ERROR' analyze.log | wc -l )" > vars.env
    artifacts:
      paths:
        - analyze.log
      expire_in: 1 week
      reports:
        dotenv: vars.env

build mobalpa-test:
    stage: deploy
    script:
      - echo $ERROR











        


      

