stages:
    - docker-build

build mobalpa-blog:
    stage: docker-build
    script:
      - export IMAGE_TAG="$CI_JOB_NAME"
      - export IMAGE_TAG_V="$CI_COMMIT_SHORT_SHA"
      - echo $IMAGE_TAG:$IMAGE_TAG_V
      #- docker build -t mobalpa-blog:0705 .






        


      

