stages:
    - docker-build
    - test

build mobalpa-blog:
    stage: docker-build
    script:
      #- echo $CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA
      - docker build -t $CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA .
      - docker run -d --name web -p 8080:80 --link dbm:mysql $CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA

build mobalpa-test:
    stage: test
    script:
      - docker exec web phpcs . > analyze.blog





        


      

