stages:
    - docker-build

build mobalpa-blog:
    stage: docker-build
    script:
      - echo $CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA
      - docker build -t $CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA .






        


      

