stages:
    - docker-build
    - test
    - analyze

build mobalpa-blog:
    stage: docker-build
    before_script:
      - apk update
      - apk add --no-cache bash
    script:
      #- echo $CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA
      - docker build -t $CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA .
      - chmod +x cleanup-container.sh
      - bash cleanup-container.sh
      - docker run -d --name web -p 8080:80 --link dbm:mysql $CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA

build mobalpa-test:
    stage: test
    script:
      - sleep 5m
      - docker exec web phpcs . > /tmp/analyze.log


build mobalpa-analyze:
    stage: analyze
    script:
      - grep "ERROR" /tmp/analyze.log







        


      

