stages:
    - docker-build
    - test
    - analyze

build mobalpa-blog:
    stage: docker-build
    before_script:
      - apk update
      - apk add --no-cache bash
    script:
      #- echo $CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA
      - docker build -t $CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA .
      - chmod +x cleanup-container.sh
      - bash cleanup-container.sh
      - docker run -d --name web -p 8080:80 --link dbm:mysql $CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA

build mobalpa-test:
    stage: test
    allow_failure: true
    script:
      #- sleep 1h
      - docker exec web /usr/local/bin/phpcs /usr/local/apache2/htdocs > /tmp/analyze.log
    artifacts:
      paths:
        - /tmp

build mobalpa-analyze:
    stage: analyze
    allow_failure: true
    script:
      - grep "ERROR" /tmp/analyze.log







        


      

